package org.example.subscription.flutterwave.payloads;

import org.example.subscription.flutterwave.domains.FlutterwaveSettings;

public class FlutterwaveSettingsDTO {
    public Long id;
    public String apiUrl;
    public String tokenUrl;
    public String clientId;
    public String secretKey;
    public String publicKey;
    public String encryptionKey;
    public String webhookSecretHash;
    public String webhookCallbackUrl;
    public String defaultEmail;
    public String defaultCurrency;
    public Boolean enabled;
    public boolean configured;
    public String updatedAt;
    public String hint;

    public static FlutterwaveSettingsDTO from(FlutterwaveSettings s) {
        FlutterwaveSettingsDTO dto = new FlutterwaveSettingsDTO();
        dto.id = s.id;
        dto.apiUrl = s.apiUrl;
        dto.tokenUrl = s.tokenUrl;
        dto.clientId = s.clientId;
        dto.secretKey = s.secretKey;
        dto.publicKey = s.publicKey;
        dto.encryptionKey = s.encryptionKey;
        dto.webhookSecretHash = s.webhookSecretHash;
        dto.webhookCallbackUrl = s.webhookCallbackUrl;
        dto.defaultEmail = s.defaultEmail;
        dto.defaultCurrency = s.defaultCurrency;
        dto.enabled = s.enabled;
        dto.configured = notBlank(s.clientId) && notBlank(s.secretKey);
        dto.updatedAt = s.updatedAt != null ? s.updatedAt.toString() : null;
        dto.hint = "Flutterwave v4: Client ID + Client Secret. Webhook secret hash is generated by us — paste the same value into Flutterwave Dashboard → Settings → Webhooks.";
        return dto;
    }

    private static boolean notBlank(String v) {
        return v != null && !v.isBlank();
    }
}