package org.example.subscription.services;

import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.WebApplicationException;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.example.subscription.services.payloads.SignedActivationPayload;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Locale;

/**
 * Verifies offline subscription tokens generated by the Flutter vendor app.
 * Format: MC1.&lt;base64url(json)&gt;.&lt;base64url(hmac-sha256)&gt;
 */
@ApplicationScoped
public class SignedActivationTokenVerifier {

    private static final String PREFIX = "MC1.";
    private static final ObjectMapper MAPPER = new ObjectMapper();

    @ConfigProperty(name = "subscription.token-signing-secret", defaultValue = "MEDIcenter-OFFLINE-SUB-2026")
    String signingSecret;

    public static boolean isSignedToken(String rawToken) {
        return rawToken != null && rawToken.trim().toUpperCase(Locale.ROOT).startsWith(PREFIX);
    }

    public SignedActivationPayload verifyAndParse(String rawToken) {
        if (rawToken == null || rawToken.isBlank()) {
            throw new WebApplicationException("Activation code is required", 400);
        }

        String token = rawToken.trim();
        if (!token.toUpperCase(Locale.ROOT).startsWith(PREFIX)) {
            throw new WebApplicationException("Invalid activation code format", 400);
        }

        String body = token.substring(PREFIX.length());
        int dot = body.lastIndexOf('.');
        if (dot <= 0 || dot >= body.length() - 1) {
            throw new WebApplicationException("Invalid activation code format", 400);
        }

        String payloadPart = body.substring(0, dot);
        String signaturePart = body.substring(dot + 1);

        byte[] payloadBytes;
        byte[] signatureBytes;
        try {
            payloadBytes = Base64.getUrlDecoder().decode(payloadPart);
            signatureBytes = Base64.getUrlDecoder().decode(signaturePart);
        } catch (IllegalArgumentException ex) {
            throw new WebApplicationException("Invalid activation code encoding", 400);
        }

        byte[] expected = sign(payloadBytes);
        if (!constantTimeEquals(expected, signatureBytes)) {
            throw new WebApplicationException("Invalid activation code signature", 403);
        }

        SignedActivationPayload payload;
        try {
            payload = MAPPER.readValue(payloadBytes, SignedActivationPayload.class);
        } catch (Exception ex) {
            throw new WebApplicationException("Invalid activation code payload", 400);
        }

        if (payload.v != 1) {
            throw new WebApplicationException("Unsupported activation code version", 400);
        }
        if (payload.jti == null || payload.jti.isBlank()) {
            throw new WebApplicationException("Activation code is missing an id", 400);
        }
        if (payload.fn == null || payload.fn.isBlank()) {
            throw new WebApplicationException("Activation code is missing facility name", 400);
        }
        if (payload.days <= 0) {
            throw new WebApplicationException("Activation code has invalid duration", 400);
        }
        if (payload.modules == null || payload.modules.isBlank()) {
            payload.modules = "all";
        }

        return payload;
    }

    private byte[] sign(byte[] payloadBytes) {
        try {
            Mac mac = Mac.getInstance("HmacSHA256");
            mac.init(new SecretKeySpec(signingSecret.getBytes(StandardCharsets.UTF_8), "HmacSHA256"));
            return mac.doFinal(payloadBytes);
        } catch (Exception ex) {
            throw new WebApplicationException("Unable to verify activation code", 500);
        }
    }

    private boolean constantTimeEquals(byte[] a, byte[] b) {
        if (a == null || b == null || a.length != b.length) {
            return false;
        }
        int result = 0;
        for (int i = 0; i < a.length; i++) {
            result |= a[i] ^ b[i];
        }
        return result == 0;
    }
}
